Repository wordpress-mobile/WordPress-FluxC-Android, pull requests merged in 2019-05, with the labels that each got.

#1230 Insights management
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_AppComponent.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_ManageInsightsTestJetpack.kt
  example/src/test/java/org/wordpress/android/fluxc/store/StatsStoreTest.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/stats/InsightTypeDataModel.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/stats/InsightTypeModel.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/InsightTypeSqlUtils.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.java
  fluxc/src/main/java/org/wordpress/android/fluxc/store/StatsStore.kt
Labels: Stats Refresh, [PR] Not Ready For Merge

#1233 Cache in granular stats
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/stats/time/VisitAndViewsRestClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/persistance/stats/time/AuthorsSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/persistance/stats/time/ClicksSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/persistance/stats/time/CountryViewsSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/persistance/stats/time/PostAndPageViewsSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/persistance/stats/time/ReferrersSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/persistance/stats/time/SearchTermsSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/persistance/stats/time/VideoPlaysSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/persistance/stats/time/VisitAndViewsSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/store/stats/time/AuthorsStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/store/stats/time/ClicksStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/store/stats/time/CountryViewsStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/store/stats/time/PostAndPageViewsStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/store/stats/time/ReferrersStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/store/stats/time/SearchTermsStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/store/stats/time/TimeStatsFixtures.kt
  example/src/test/java/org/wordpress/android/fluxc/store/stats/time/VideoPlaysStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/store/stats/time/VisitsAndViewsStoreTest.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/stats/time/VisitAndViewsRestClient.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/StatsRequestSqlUtils.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/StatsSqlUtils.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/TimeStatsSqlUtils.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/stats/time/AuthorsStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/stats/time/ClicksStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/stats/time/CountryViewsStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/stats/time/PostAndPageViewsStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/stats/time/ReferrersStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/stats/time/SearchTermsStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/stats/time/VideoPlaysStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/stats/time/VisitsAndViewsStore.kt
Labels: Stats Refresh

#1235 Woo: 1 of 3 - Add support for list management for order list
  example/build.gradle
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_AppComponent.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_WCOrderListTest.kt
  example/src/androidTest/java/org/wordpress/android/fluxc/release/utils/TestWCOrderListDataSource.kt
  example/src/debug/java/org/wordpress/android/fluxc/example/di/AppComponentDebug.kt
  example/src/main/AndroidManifest.xml
  example/src/main/java/org/wordpress/android/fluxc/example/OrderListAdapter.kt
  example/src/main/java/org/wordpress/android/fluxc/example/WCOrderFetcher.kt
  example/src/main/java/org/wordpress/android/fluxc/example/WCOrderListActivity.kt
  example/src/main/java/org/wordpress/android/fluxc/example/WooCommerceFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/di/ActivityScope.kt
  example/src/main/java/org/wordpress/android/fluxc/example/di/AppComponent.kt
  example/src/main/java/org/wordpress/android/fluxc/example/di/WCOrderListActivityModule.kt
  example/src/main/res/drawable/ic_check.xml
  example/src/main/res/drawable/ic_clear.xml
  example/src/main/res/layout/activity_wc_order_list.xml
  example/src/main/res/layout/fragment_woocommerce.xml
  example/src/main/res/layout/list_item_skeleton.xml
  example/src/main/res/layout/list_item_woo_order.xml
  plugins/woocommerce/src/main/java/org/wordpress/android/fluxc/action/WCOrderAction.java
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/WCOrderListDescriptor.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/OrderSqlUtils.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCOrderStore.kt
Labels: [Store] Woo: Order

#1246 Fix failing insights test
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_ManageInsightsTestJetpack.kt
Labels: Stats Refresh, Tests

#1243 Add PostStore.getLocalDrafts
  example/src/test/java/org/wordpress/android/fluxc/page/PageStoreLocalDraftTest.kt
  example/src/test/java/org/wordpress/android/fluxc/post/PostStoreUnitTest.java
  example/src/test/java/org/wordpress/android/fluxc/post/PostTestUtils.java
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/PostSqlUtils.java
  fluxc/src/main/java/org/wordpress/android/fluxc/store/PageStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/PostStore.java
Labels: [Type] enhancement

#1253 Remove unused /is-available/domain/ feature
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_AccountAvailabilityTest.java
  example/src/test/java/org/wordpress/android/fluxc/endpoints/WPComEndpointTest.java
  fluxc/src/main/java/org/wordpress/android/fluxc/action/AccountAction.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/account/AccountRestClient.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/account/IsAvailableResponse.java
  fluxc/src/main/java/org/wordpress/android/fluxc/store/AccountStore.java
  fluxc/src/main/tools/wp-com-endpoints.txt
Labels: Tests

#1250 Added logic to fetch and cache a store's country name in WcSettingsModel
  example/src/androidTest/java/org/wordpress/android/fluxc/mocked/MockedStack_WCBaseStoreTest.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.java
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/WCSettingsModel.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/WooCommerceRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/WCSettingsSqlUtils.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WooCommerceStore.kt
Labels: [Store] WooCommerce

#1254 Convert WPComRestResponse to Kotlin
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/GeoLocation.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/GeoLocation.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/PostParent.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/PostParent.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/PostRestClient.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/PostWPComRestResponse.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/PostWPComRestResponse.kt
Labels: Tech debt

#1256 Adds message when authentication fails when running WPCom tests
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_WPComBase.java
Labels: Tests

#1225 Woo: Clean up the woo test page in the example app
  .idea/codeStyles/Project.xml
  example/src/main/java/org/wordpress/android/fluxc/example/FragmentExt.kt
  example/src/main/java/org/wordpress/android/fluxc/example/MainFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/di/FragmentsModule.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/WooCommerceFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/orders/WooOrdersFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooProductsFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/stats/WooStatsFragment.kt
  example/src/main/res/layout/fragment_woo_orders.xml
  example/src/main/res/layout/fragment_woo_products.xml
  example/src/main/res/layout/fragment_woo_stats.xml
  example/src/main/res/layout/fragment_woocommerce.xml
Labels: [Store] WooCommerce

#1260 Remove connected cart redemption test
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_TransactionsTest.kt
Labels: Tests

#1255 Issue/1247 remote auto save
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_PostTestWPCom.java
  example/src/test/java/org/wordpress/android/fluxc/persistence/PostSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/utils/ObjectsUtilsTest.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/action/PostAction.java
  fluxc/src/main/java/org/wordpress/android/fluxc/model/CauseOfOnPostChanged.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/PostModel.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/PostRemoteAutoSaveModel.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/PostRestClient.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/PostWPComRestResponse.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/post/PostXMLRPCClient.java
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/PostSqlUtils.java
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.java
  fluxc/src/main/java/org/wordpress/android/fluxc/store/PostStore.java
  fluxc/src/main/java/org/wordpress/android/fluxc/utils/ObjectsUtils.java
  fluxc/src/main/tools/wp-com-endpoints.txt
Labels: [Store] Post

#1259 Remove shared mPost field in ReleaseStack_PostTestWPCom
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_PostTestWPCom.java
Labels: [Type] enhancement

#1262 Revert: Convert GeoLocation and PostParent to kotlin
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/GeoLocation.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/GeoLocation.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/PostParent.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/PostParent.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/PostRestClient.java
Labels: Tests, [Pri] High

#1266 Issue/fluxc dagger upgrade
  build.gradle
  example/src/main/java/org/wordpress/android/fluxc/example/di/AppComponent.kt
Labels: AndroidX

#1267 Restore accidentally deleted Project.xml IDEA config file
  .idea/codeStyles/Project.xml
Labels: Core

#1270 Make PostSqlUtils mockable
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_PostTestWPCom.java
  example/src/test/java/org/wordpress/android/fluxc/page/PageStoreLocalDraftTest.kt
  example/src/test/java/org/wordpress/android/fluxc/page/PageStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/post/PostStoreUnitTest.java
  example/src/test/java/org/wordpress/android/fluxc/site/SiteStoreUnitTest.java
  example/src/test/java/org/wordpress/android/fluxc/upload/UploadSqlUtilsTest.java
  example/src/test/java/org/wordpress/android/fluxc/upload/UploadStoreUnitTest.java
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/PostSqlUtils.java
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/SiteSqlUtils.java
  fluxc/src/main/java/org/wordpress/android/fluxc/store/PageStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/PostStore.java
  fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.java
Labels: Tech debt

#1269 Add test for page remote-auto-save
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_PostTestWPCom.java
Labels: Tests, [Store] Post

#1271 Make PageStore.getLocalDraftPages return PostModel
  example/src/test/java/org/wordpress/android/fluxc/page/PageStoreLocalDraftTest.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/PageStore.kt
Labels: [Type] enhancement

#1239 Check null response object for device register api & order stats fetc…
  example/src/androidTest/java/org/wordpress/android/fluxc/mocked/MockedStack_NotificationTest.kt
  example/src/androidTest/java/org/wordpress/android/fluxc/mocked/MockedStack_WCStatsTest.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/notifications/NotificationRestClient.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/NotificationStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/orderstats/OrderStatsRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCStatsStore.kt
Labels: [Store] Woo: Stats

#1252 Bump eventbus to 3.1.1
  fluxc/build.gradle
Labels: Tech debt

#1265 Add insights management news card
  example/src/test/java/org/wordpress/android/fluxc/store/StatsStoreTest.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/StatsStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/utils/PreferenceUtils.kt
Labels: Stats Refresh

#1276 Add unit tests for PostStore.handleFetchedPostList method
  example/src/test/java/org/wordpress/android/fluxc/post/PostStoreDbIntegrationTest.java
  example/src/test/java/org/wordpress/android/fluxc/post/PostStoreTest.kt
Labels: Tests, [Store] Post
