Repository wordpress-mobile/WordPress-FluxC-Android, pull requests merged in 2021-06, with the labels that each got.

#1828 Add an optional task to CI to run connected tests
  .circleci/config.yml
Labels: Tooling

#2015 Added timestamp to comment response from self hosted site.
  fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/comment/CommentXMLRPCClient.java
Labels: [Store] Comment

#2017 RewindStatusModel.State: Fix awaiting credentials value
  fluxc/src/main/java/org/wordpress/android/fluxc/model/activity/RewindStatusModel.kt
Labels: Jetpack App

#2010 Blogging reminders repository
  build.gradle
  example/build.gradle
  example/src/debug/java/org/wordpress/android/fluxc/example/di/AppComponentDebug.kt
  example/src/main/java/org/wordpress/android/fluxc/example/di/AppComponent.kt
  example/src/test/java/org/wordpress/android/fluxc/model/BloggingRemindersMapperTest.kt
  example/src/test/java/org/wordpress/android/fluxc/store/BloggingRemindersStoreTest.kt
  fluxc/build.gradle
  fluxc/src/main/java/org/wordpress/android/fluxc/model/BloggingRemindersMapper.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/BloggingRemindersModel.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/module/DatabaseModule.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/BloggingRemindersDao.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WPAndroidDatabase.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/BloggingRemindersStore.kt
  instaflux/src/main/java/org/wordpress/android/fluxc/instaflux/AppComponent.java
Labels: [Type] enhancement

#2019 Convert SiteStore to Kotlin
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_DiscoveryTest.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_FluxCImageLoaderTest.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_SiteTestJetpack.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_SiteTestXMLRPC.java
  example/src/main/java/org/wordpress/android/fluxc/example/MainFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/SiteSelectorDialog.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClient.java
  fluxc/src/main/java/org/wordpress/android/fluxc/store/JetpackStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.java
  fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.kt
  instaflux/src/main/java/org/wordpress/android/fluxc/instaflux/MainInstafluxActivity.java
Labels: Tech debt, [Type] enhancement

#2014 Shipping Labels: add "email_receipts" parameter to the purchase flow
  example/src/main/java/org/wordpress/android/fluxc/example/ui/shippinglabels/WooShippingLabelFragment.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/shippinglabels/WCShippingLabelStoreTest.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/shippinglabels/ShippingLabelRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCShippingLabelStore.kt
Labels: [Store] Woo: Shipping Label, [Type] enhancement

#2025 Woo: fix NPE if shipping_lines is missing from refunds response
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/refunds/RefundMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/refunds/RefundRestClient.kt
Labels: [Store] Woo: Refunds, [Type] bug

#2020 Extract site sql utils from site store
  example/src/androidTest/java/org/wordpress/android/fluxc/mocked/MockedStack_WCProductsTest.kt
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_WCBase.kt
  example/src/main/java/org/wordpress/android/fluxc/example/SitesFragment.java
  example/src/test/java/org/wordpress/android/fluxc/TestSiteSqlUtils.kt
  example/src/test/java/org/wordpress/android/fluxc/site/SiteStoreUnitTest.java
  example/src/test/java/org/wordpress/android/fluxc/store/ReactNativeStoreWPAPITest.kt
  example/src/test/java/org/wordpress/android/fluxc/store/ReactNativeStoreWpComTest.kt
  example/src/test/java/org/wordpress/android/fluxc/theme/ThemeStoreUnitTest.java
  example/src/test/java/org/wordpress/android/fluxc/wc/WooCommerceStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/data/WCDataStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/order/OrderSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/order/OrderTestUtils.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/product/ProductSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/shippinglabels/WCShippingLabelSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/shippinglabels/WCShippingLabelStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/taxes/WCTaxSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/taxes/WCTaxStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/user/WCUserSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/user/WCUserStoreTest.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/SiteSqlUtils.java
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/SiteSqlUtils.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/ReactNativeStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WooCommerceStore.kt
Labels: Tech debt, [Type] enhancement

#2021 Convert site rest client to kotlin
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClient.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClient.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.kt
Labels: Tech debt

#2022 Convert site xmlrpc rest client to kotlin
  example/src/test/java/org/wordpress/android/fluxc/site/SiteXMLRPCClientTest.java
  example/src/test/java/org/wordpress/android/fluxc/site/SiteXMLRPCClientTest.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/site/SiteXMLRPCClient.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/site/SiteXMLRPCClient.kt
Labels: Tech debt

#2023 Convert site store methods to coroutines
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/activity/ActivityLogRestClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/jetpacktunnel/JetpackRestClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/scan/ScanRestClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteHomepageRestClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/stats/time/ReferrersRestClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/site/SiteStoreUnitTest.java
  example/src/test/java/org/wordpress/android/fluxc/site/SiteXMLRPCClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/store/SiteStoreTest.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/action/SiteAction.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/WPComGsonRequestBuilder.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/NewSiteResponse.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClient.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteWPComRestResponse.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/XMLRPCRequestBuilder.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/site/SiteXMLRPCClient.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.kt
Labels: Tech debt

#2016 Woo Shipping Labels: add support for commercial invoices
  example/src/main/java/org/wordpress/android/fluxc/example/ui/shippinglabels/WooShippingLabelFragment.kt
  example/src/main/res/layout/fragment_woo_shippinglabels.xml
  example/src/main/res/xml/provider_paths.xml
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/shippinglabels/WCShippingLabelMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/shippinglabels/WCShippingLabelModel.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/shippinglabels/LabelItem.kt
Labels: [Store] Woo: Shipping Label, [Type] enhancement

#2027 Release 1.19.0
  .circleci/config.yml
  build.gradle
  example/build.gradle
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_WCPayTest.kt
  example/src/debug/java/org/wordpress/android/fluxc/example/di/AppComponentDebug.kt
  example/src/main/java/org/wordpress/android/fluxc/example/di/AppComponent.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/shippinglabels/WooShippingLabelFragment.kt
  example/src/main/res/layout/fragment_woo_shippinglabels.xml
  example/src/main/res/xml/provider_paths.xml
  example/src/test/java/org/wordpress/android/fluxc/model/BloggingRemindersMapperTest.kt
  example/src/test/java/org/wordpress/android/fluxc/store/BloggingRemindersStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/shippinglabels/WCShippingLabelStoreTest.kt
  fluxc-processor/src/main/resources/wc-wp-api-endpoints.txt
  fluxc/build.gradle
  fluxc/src/main/java/org/wordpress/android/fluxc/model/BloggingRemindersMapper.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/BloggingRemindersModel.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/activity/RewindStatusModel.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/module/DatabaseModule.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/comment/CommentXMLRPCClient.java
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/BloggingRemindersDao.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WPAndroidDatabase.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/BloggingRemindersStore.kt
  instaflux/src/main/java/org/wordpress/android/fluxc/instaflux/AppComponent.java
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/pay/WCCapturePaymentResponsePayload.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/pay/WCPaymentAccountResult.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/refunds/RefundMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/shippinglabels/WCShippingLabelMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/shippinglabels/WCShippingLabelModel.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/pay/PayRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/refunds/RefundRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/shippinglabels/LabelItem.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/shippinglabels/ShippingLabelRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCPayStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCShippingLabelStore.kt
Labels: Releases

#2028 Woo: add a common class that represents object's meta data
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/WCMetaData.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/WCOrderModel.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/order/OrderProductAttributeListDeserializer.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/refunds/RefundMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/refunds/WCRefundModel.kt
Labels: [PR] Not Ready For Merge, [Store] Woo: Order, [Store] Woo: Refunds

#2026 Re-enable fetchstyle plugin and request it from s3 repository
  build.gradle
  settings.gradle
Labels: Tooling

#2029 Woo: fetch and expose order's meta data
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/WCOrderModel.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderApiResponse.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderRestClient.kt
Labels: [Store] Woo: Order

#2032 Add API endpoint support for adding custom packages/activating predefined packages.
  example/src/main/java/org/wordpress/android/fluxc/example/ui/shippinglabels/WooShippingLabelFragment.kt
  example/src/main/res/layout/fragment_woo_shippinglabels.xml
  example/src/test/java/org/wordpress/android/fluxc/wc/shippinglabels/WCShippingLabelStoreTest.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/shippinglabels/WCPackagesResult.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/shippinglabels/ShippingLabelRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCShippingLabelStore.kt
Labels: [Store] Woo: Shipping Label

#2013 Move `WCOrderFetcher` to FluxC. Fetch outdated and missing orders together.
  example/src/main/java/org/wordpress/android/fluxc/example/WCOrderFetcher.kt
  example/src/main/java/org/wordpress/android/fluxc/example/WCOrderListActivity.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/order/OrderTestUtils.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/order/WCOrderStoreTest.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCOrderFetcher.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCOrderStore.kt
Labels: [Store] Woo: Order, [Type] enhancement

#2018 SiteStore refactoring - feature PR
  example/src/androidTest/java/org/wordpress/android/fluxc/mocked/MockedStack_WCProductsTest.kt
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_DiscoveryTest.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_FluxCImageLoaderTest.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_SiteTestJetpack.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_SiteTestXMLRPC.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_WCBase.kt
  example/src/main/java/org/wordpress/android/fluxc/example/MainFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/SiteSelectorDialog.kt
  example/src/main/java/org/wordpress/android/fluxc/example/SitesFragment.java
  example/src/test/java/org/wordpress/android/fluxc/TestSiteSqlUtils.kt
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/activity/ActivityLogRestClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/jetpacktunnel/JetpackRestClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/scan/ScanRestClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteHomepageRestClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/stats/time/ReferrersRestClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/site/SiteStoreUnitTest.java
  example/src/test/java/org/wordpress/android/fluxc/site/SiteXMLRPCClientTest.java
  example/src/test/java/org/wordpress/android/fluxc/site/SiteXMLRPCClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/store/ReactNativeStoreWPAPITest.kt
  example/src/test/java/org/wordpress/android/fluxc/store/ReactNativeStoreWpComTest.kt
  example/src/test/java/org/wordpress/android/fluxc/store/SiteStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/theme/ThemeStoreUnitTest.java
  example/src/test/java/org/wordpress/android/fluxc/wc/WooCommerceStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/data/WCDataStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/order/OrderSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/order/OrderTestUtils.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/product/ProductSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/shippinglabels/WCShippingLabelSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/shippinglabels/WCShippingLabelStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/taxes/WCTaxSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/taxes/WCTaxStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/user/WCUserSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/user/WCUserStoreTest.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/action/SiteAction.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/WPComGsonRequestBuilder.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/NewSiteResponse.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClient.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClient.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteWPComRestResponse.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/XMLRPCRequestBuilder.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/site/SiteXMLRPCClient.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/site/SiteXMLRPCClient.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/SiteSqlUtils.java
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/SiteSqlUtils.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/JetpackStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/ReactNativeStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.java
  fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.kt
  instaflux/src/main/java/org/wordpress/android/fluxc/instaflux/MainInstafluxActivity.java
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WooCommerceStore.kt
Labels: Tech debt, [Type] enhancement

#2035 Making SiteSTore open to allow mocking in androidTest.
  fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.kt
Labels: Tests, [Type] bug

#2038 Check blogging reminders presence
  example/src/test/java/org/wordpress/android/fluxc/store/BloggingRemindersStoreTest.kt
  fluxc/schemas/org.wordpress.android.fluxc.persistence.WPAndroidDatabase/1.json
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/BloggingRemindersDao.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/BloggingRemindersStore.kt
Labels: [Type] enhancement

#1940 [Global Styles] Implements Global Styles API Call
  example/src/androidTest/java/org/wordpress/android/fluxc/mocked/MockedStack_EditorThemeStoreTest.kt
  example/src/androidTest/resources/global-styles-full-success.json
  example/src/androidTest/resources/global-styles-off-success.json
  fluxc/src/main/java/org/wordpress/android/fluxc/model/EditorTheme.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/EditorThemeSqlUtils.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/EditorThemeStore.kt
Labels: [Type] enhancement

#2041 Strips semantic version information in GSS version check
  fluxc/src/main/java/org/wordpress/android/fluxc/store/EditorThemeStore.kt
Labels: [Type] bug

#2037 Change custom's item quantity to Int
  example/src/main/java/org/wordpress/android/fluxc/example/ui/shippinglabels/WooShippingLabelFragment.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/shippinglabels/WCShippingPackageCustoms.kt
Labels: [PR] Not Ready For Merge, [Store] Woo: Shipping Label
