Repository wordpress-mobile/WordPress-FluxC-Android, pull requests merged in 2021-03, with the labels that each got.

#1902 Issue-3605. Fetch a customer
  example/build.gradle
  example/src/test/java/org/wordpress/android/fluxc/model/customer/WCCustomerMapperTest.kt
  example/src/test/java/org/wordpress/android/fluxc/persistence/CustomerSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/store/WCCustomerStoreTest.kt
  fluxc-processor/src/main/resources/wc-wp-api-endpoints.txt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/customer/WCCustomerMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/customer/WCCustomerModel.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/module/ReleaseWCNetworkModule.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/customer/CustomerRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/customer/dto/CustomerApiResponse.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/CustomerSqlUtils.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCCustomerStore.kt
  tests/api/src/test/java/APITesting_WCCustomer.java
Labels: [Store] Woo: Order

#1890 Updates the starter designs endpoint and adds preview_height parameter in layout calls
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_SiteTestWPCom.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_SiteTestXMLRPC.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_ThemeTestWPCom.java
  fluxc-processor/src/main/resources/wp-com-endpoints.txt
  fluxc-processor/src/main/resources/wp-com-v2-endpoints.txt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/StarterDesignModel.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClient.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/theme/StarterDesignsResponse.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/theme/ThemeRestClient.java
  fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.java
  fluxc/src/main/java/org/wordpress/android/fluxc/store/ThemeStore.java
Labels: [Type] enhancement

#1905 Issue-3605. Example of customer fetching
  example/src/main/java/org/wordpress/android/fluxc/example/NotificationsFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/di/FragmentsModule.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/WooCommerceFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/common/FragmentExt.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/customer/WooCustomersFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooProductsFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/shippinglabels/WooShippingLabelFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/stats/WooRevenueStatsFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/taxes/WooTaxFragment.kt
  example/src/main/res/layout/fragment_woo_customer.xml
  example/src/main/res/layout/fragment_woocommerce.xml
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/customer/WCCustomerModel.kt
Labels: [Store] Woo: Order

#1909 Woo Shipping Labels: purchase labels
  example/src/main/java/org/wordpress/android/fluxc/example/ui/shippinglabels/WooShippingLabelFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/utils/AlertDialogUtils.kt
  example/src/main/res/layout/fragment_woo_shippinglabels.xml
  example/src/test/java/org/wordpress/android/fluxc/wc/shippinglabels/WCShippingLabelStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/shippinglabels/WCShippingLabelTestUtils.kt
  example/src/test/resources/wc/purchase-shipping-labels.json
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/shippinglabels/WCShippingLabelMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/shippinglabels/WCShippingLabelModel.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/shippinglabels/WCShippingLabelPackageData.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/shippinglabels/LabelItem.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/shippinglabels/PurchaseShippingLabelApiResponse.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/shippinglabels/ShippingLabelApiResponse.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/shippinglabels/ShippingLabelRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCShippingLabelStore.kt
Labels: [Store] Woo: Shipping Label, [Type] enhancement

#1914 Merge release/1.12.0 -> trunk
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_SiteTestWPCom.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_SiteTestXMLRPC.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_ThemeTestWPCom.java
  example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooProductAttributeFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooProductsFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooUpdateProductFragment.kt
  example/src/main/res/layout/fragment_woo_product_attribute.xml
  example/src/main/res/layout/fragment_woo_products.xml
  example/src/main/res/layout/fragment_woo_update_product.xml
  example/src/test/java/org/wordpress/android/fluxc/site/SiteStoreUnitTest.java
  example/src/test/java/org/wordpress/android/fluxc/wc/order/WCOrderModelTest.kt
  example/src/test/resources/wc/order-shipping-lines.json
  fluxc-processor/src/main/resources/wp-com-endpoints.txt
  fluxc-processor/src/main/resources/wp-com-v2-endpoints.txt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/StarterDesignModel.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/layouts/GutenbergLayoutCategoryModel.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/layouts/GutenbergLayoutModel.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/BlockLayoutsResponse.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClient.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/theme/StarterDesignsResponse.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/theme/ThemeRestClient.java
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.java
  fluxc/src/main/java/org/wordpress/android/fluxc/store/ThemeStore.java
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/WCOrderModel.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/attribute/WCGlobalAttributeModel.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/shippinglabels/WCShippingAccountSettings.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/shippinglabels/WCShippingLabelPaperSize.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/product/ProductRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/shippinglabels/AccountSettingsApiResponse.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCGlobalAttributeStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCProductStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCShippingLabelStore.kt
Labels: Releases

#1916 Issue/1915 hackweek db downgrade
  fluxc/gradle.properties-example
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
Labels: Tech debt

#1888 Return comment filter with response and add a limit option for local comment requests.
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_CommentTestWPCom.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_CommentTestXMLRPC.java
  example/src/main/java/org/wordpress/android/fluxc/example/CommentsFragment.java
  example/src/test/java/org/wordpress/android/fluxc/comment/CommentSqlUtilsTest.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/CommentModel.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/comment/CommentRestClient.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/comment/CommentXMLRPCClient.java
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/CommentSqlUtils.java
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/CommentStore.java
  fluxc/src/main/java/org/wordpress/android/fluxc/utils/CommentErrorUtils.java
Labels: [Store] Comment

#1921 Issue/1919 hack week cleanup example main
  .idea/codeStyles/Project.xml
  example/gradle.properties-example
  example/src/main/res/layout/fragment_account.xml
  example/src/main/res/layout/fragment_comments.xml
  example/src/main/res/layout/fragment_editor_theme.xml
  example/src/main/res/layout/fragment_experiments.xml
  example/src/main/res/layout/fragment_main.xml
  example/src/main/res/layout/fragment_media.xml
  example/src/main/res/layout/fragment_notifications.xml
  example/src/main/res/layout/fragment_posts.xml
  example/src/main/res/layout/fragment_signed_out_actions.xml
  example/src/main/res/layout/fragment_sites.xml
  example/src/main/res/layout/fragment_taxonomies.xml
  example/src/main/res/layout/fragment_themes.xml
  example/src/main/res/layout/fragment_uploads.xml
  example/src/main/res/layout/fragment_woocommerce.xml
  example/src/main/res/values/dimens.xml
  example/src/main/res/values/styles.xml
Labels: Tech debt, [Type] enhancement

#1923 Issue/1922 hack week cleanup example toolbar
  example/src/main/AndroidManifest.xml
  example/src/main/java/org/wordpress/android/fluxc/example/MainExampleActivity.kt
  example/src/main/res/layout/activity_example.xml
  example/src/main/res/values/styles.xml
Labels: [Type] enhancement

#1924 Issue/1919 hack week cleanup example woo
  example/src/main/res/layout/fragment_woo_gateways.xml
  example/src/main/res/layout/fragment_woo_leaderboards.xml
  example/src/main/res/layout/fragment_woo_orders.xml
  example/src/main/res/layout/fragment_woo_product_attribute.xml
  example/src/main/res/layout/fragment_woo_product_categories.xml
  example/src/main/res/layout/fragment_woo_product_downloads.xml
  example/src/main/res/layout/fragment_woo_product_filters.xml
  example/src/main/res/layout/fragment_woo_products.xml
  example/src/main/res/layout/fragment_woo_refunds.xml
  example/src/main/res/layout/fragment_woo_revenue_stats.xml
  example/src/main/res/layout/fragment_woo_shippinglabels.xml
  example/src/main/res/layout/fragment_woo_stats.xml
  example/src/main/res/layout/fragment_woo_taxes.xml
  example/src/main/res/layout/fragment_woo_update_product.xml
  example/src/main/res/layout/fragment_woo_update_variation.xml
  example/src/main/res/layout/fragment_woo_verify_address.xml
  example/src/main/res/layout/fragment_woocommerce.xml
  example/src/main/res/values/styles.xml
Labels: [Type] enhancement

#1920 Woo: Customers endpoint
  example/build.gradle
  example/src/main/java/org/wordpress/android/fluxc/example/FragmentExt.kt
  example/src/main/java/org/wordpress/android/fluxc/example/NotificationsFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/di/FragmentsModule.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/WooCommerceFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/common/FragmentExt.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/customer/WooCustomersFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/customer/creation/WooCustomerCreationFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/customer/search/SearchCustomerListDescriptor.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/customer/search/WooCustomersListItemDataSource.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/customer/search/WooCustomersSearchAdapter.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/customer/search/WooCustomersSearchBuilderFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/customer/search/WooCustomersSearchFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooProductsFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/shippinglabels/WooShippingLabelFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/stats/WooRevenueStatsFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/taxes/WooTaxFragment.kt
  example/src/main/res/layout/fragment_woo_customer.xml
  example/src/main/res/layout/fragment_woo_customer_creation.xml
  example/src/main/res/layout/fragment_woo_customers_search.xml
  example/src/main/res/layout/fragment_woo_customers_search_builder.xml
  example/src/main/res/layout/fragment_woocommerce.xml
  example/src/main/res/layout/list_item_woo_customer.xml
  example/src/test/java/org/wordpress/android/fluxc/model/customer/WCCustomerMapperTest.kt
  example/src/test/java/org/wordpress/android/fluxc/persistence/CustomerSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/store/WCCustomerStoreTest.kt
  fluxc-processor/src/main/resources/wc-wp-api-endpoints.txt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/customer/WCCustomerListDescriptor.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/customer/WCCustomerMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/customer/WCCustomerModel.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/module/ReleaseWCNetworkModule.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/customer/CustomerRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/customer/CustomerSorting.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/customer/dto/CustomerDTO.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/CustomerSqlUtils.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCCustomerStore.kt
  tests/api/src/test/java/APITesting_WCCustomer.java
Labels: [Store] Woo: Order

#1893 Add button field to formattable content
  example/src/test/java/org/wordpress/android/fluxc/tools/FormattableContentMapperTest.kt
  example/src/test/resources/notifications/body-response.json
  fluxc/src/main/java/org/wordpress/android/fluxc/tools/FormattableContentMapper.kt
Labels: [Type] enhancement

#1925 Fix breaking tests: Use unique content for WPCom post tests
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_PostTestWPCom.java
Labels: Tests

#1926 Fix first day of week
  example/src/test/java/org/wordpress/android/fluxc/wc/utils/DateUtilsTest.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCStatsStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/utils/DateUtils.kt
Labels: [Store] Woo: Stats

#1929 Remove the failing API call
  tests/api/src/test/java/APITesting_WCCustomer.java
Labels: [Store] WooCommerce

#1928 Update eventbus to v3.2.0
  fluxc/build.gradle
Labels: Tech debt, [PR] Not Ready For Merge

#1933 Make attributeList a mutable field instead of a lazy single instance
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/WCProductVariationModel.kt
Labels: [Store] Woo: Product
