Repository wordpress-mobile/WordPress-FluxC-Android, pull requests merged in 2021-05, with the labels that each got.

#1984 Added endpoint to fetch user info for a store
  example/src/main/java/org/wordpress/android/fluxc/example/ui/WooCommerceFragment.kt
  example/src/main/res/layout/fragment_woocommerce.xml
  example/src/test/java/org/wordpress/android/fluxc/endpoints/WPAPIEndpointTest.java
  example/src/test/java/org/wordpress/android/fluxc/wc/user/WCUserStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/user/WCUserTestUtils.kt
  example/src/test/resources/wc/store-user-role.json
  fluxc-processor/src/main/resources/wp-api-endpoints.txt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/user/WCUserMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/user/WCUserRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/user/WCUserRole.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/user/WCUserStore.kt
Labels: [Store] WooCommerce

#1911 Site plan support for MimeTypes
  example/src/test/java/org/wordpress/android/fluxc/utils/MimeTypesTest.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/utils/MimeTypes.kt
Labels: [Type] enhancement

#1990 Support `_fields` when fetching list of orders by ids
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_WCOrderTest.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderApiResponse.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderRestClient.kt
Labels: [Store] Woo: Order, [Type] enhancement

#1991 Recreate WCRefunds database to take into account changes in PR 1948.
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
Labels: [Store] Woo: Order, [Store] Woo: Refunds

#1996 Merge release/1.16.2 into develop
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
Labels: Releases

#1973 Use Plugin DSL
  build.gradle
  example/build.gradle
  fluxc-processor/build.gradle
  fluxc/build.gradle
  instaflux/build.gradle
  plugins/woocommerce/build.gradle
  settings.gradle
Labels: Tech debt, Tooling

#1998 Revert "Use Plugin DSL"
  build.gradle
  example/build.gradle
  fluxc-processor/build.gradle
  fluxc/build.gradle
  instaflux/build.gradle
  plugins/woocommerce/build.gradle
  settings.gradle
Labels: Tech debt, Tooling, [Pri] Blocking, [Type] Crash

#1995 Adds option to return cached page layouts when available
  example/src/androidTest/java/org/wordpress/android/fluxc/TestUtils.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_SiteTestWPCom.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_SiteTestXMLRPC.java
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/SiteSqlUtils.java
  fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.java
Labels: [PR] Not Ready For Merge, [Store] Site, [Type] enhancement

#2003 Jetpack App (Basics): Add jetpack scheme
  fluxc/src/main/java/org/wordpress/android/fluxc/store/AccountStore.java
Labels: Jetpack App

#2004 Merge release/1.17.0 to trunk
  build.gradle
  example/build.gradle
  example/src/androidTest/java/org/wordpress/android/fluxc/TestUtils.java
  example/src/androidTest/java/org/wordpress/android/fluxc/mocked/MockedStack_WCPayTest.kt
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_SiteTestWPCom.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_SiteTestXMLRPC.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_WCOrderTest.kt
  example/src/androidTest/resources/wc-pay-capture-terminal-payment-response-capture-error.json
  example/src/androidTest/resources/wc-pay-capture-terminal-payment-response-missing-order.json
  example/src/androidTest/resources/wc-pay-capture-terminal-payment-response-success.json
  example/src/androidTest/resources/wc-pay-capture-terminal-payment-response-uncapturable.json
  example/src/androidTest/resources/wc-pay-capture-terminal-payment-response-unexpected-error.json
  example/src/main/java/org/wordpress/android/fluxc/example/ui/WooCommerceFragment.kt
  example/src/main/res/layout/fragment_woocommerce.xml
  example/src/test/java/org/wordpress/android/fluxc/endpoints/WPAPIEndpointTest.java
  example/src/test/java/org/wordpress/android/fluxc/utils/MimeTypesTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/user/WCUserStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/user/WCUserTestUtils.kt
  example/src/test/resources/wc/store-user-role.json
  fluxc-processor/build.gradle
  fluxc-processor/src/main/resources/wp-api-endpoints.txt
  fluxc/build.gradle
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/SiteSqlUtils.java
  fluxc/src/main/java/org/wordpress/android/fluxc/store/AccountStore.java
  fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.java
  fluxc/src/main/java/org/wordpress/android/fluxc/utils/MimeTypes.kt
  instaflux/build.gradle
  jitpack.yml
  plugins/woocommerce/build.gradle
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/pay/WCCapturePaymentResponsePayload.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderApiResponse.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/pay/PayRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/user/WCUserMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/user/WCUserRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/user/WCUserRole.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/user/WCUserStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCPayStore.kt
  settings.gradle
Labels: Releases

#2002 Woo: Adds option to fetch user name + role of the current user
  example/src/main/java/org/wordpress/android/fluxc/example/ui/WooCommerceFragment.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/user/WCUserSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/user/WCUserStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/user/WCUserTestUtils.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/user/WCUserMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/user/WCUserModel.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/user/WCUserRole.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/user/WCUserMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/user/WCUserRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/WCUserSqlUtils.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCUserStore.kt
Labels: [Store] WooCommerce

#2006 Shipping Labels: support customs form
  example/src/main/java/org/wordpress/android/fluxc/example/ui/shippinglabels/WooShippingLabelFragment.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/shippinglabels/WCShippingLabelStoreTest.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/shippinglabels/WCShippingLabelPackageData.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/shippinglabels/WCShippingPackageCustoms.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/shippinglabels/ShippingLabelRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCShippingLabelStore.kt
Labels: [Store] Woo: Shipping Label, [Type] enhancement

#2008 Add configure plugin 0.6.0
  .circleci/config.yml
  build.gradle
  example/build.gradle
  example/src/androidTest/java/org/wordpress/android/fluxc/LogEncrypterTest.kt
  example/src/androidTest/java/org/wordpress/android/fluxc/mocked/MockedStack_WCPayTest.kt
  settings.gradle
Labels: Tooling

#2005 Adding error subtype for malformed media argument.
  example/src/test/java/org/wordpress/android/fluxc/media/MediaErrorSubTypeTest.kt
  example/src/test/java/org/wordpress/android/fluxc/upload/MediaUploadModelTest.java
  fluxc/src/main/java/org/wordpress/android/fluxc/model/MediaUploadModel.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/BaseUploadRequestBody.java
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/MediaStore.java
  fluxc/src/main/java/org/wordpress/android/fluxc/store/UploadStore.java
  fluxc/src/main/java/org/wordpress/android/fluxc/store/media/MediaErrorSubType.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/utils/MediaUtils.java
Labels: [Store] Media, [Store] Upload, [Type] enhancement

#2009 Updates configure plugin to 0.6.1
  settings.gradle
Labels: Tooling

#2011 Release 1.18.0
  .circleci/config.yml
  build.gradle
  example/build.gradle
  example/src/androidTest/java/org/wordpress/android/fluxc/LogEncrypterTest.kt
  example/src/androidTest/java/org/wordpress/android/fluxc/mocked/MockedStack_WCPayTest.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/WooCommerceFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/shippinglabels/WooShippingLabelFragment.kt
  example/src/test/java/org/wordpress/android/fluxc/media/MediaErrorSubTypeTest.kt
  example/src/test/java/org/wordpress/android/fluxc/upload/MediaUploadModelTest.java
  example/src/test/java/org/wordpress/android/fluxc/wc/shippinglabels/WCShippingLabelStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/user/WCUserSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/user/WCUserStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/user/WCUserTestUtils.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/MediaUploadModel.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/BaseUploadRequestBody.java
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/MediaStore.java
  fluxc/src/main/java/org/wordpress/android/fluxc/store/UploadStore.java
  fluxc/src/main/java/org/wordpress/android/fluxc/store/media/MediaErrorSubType.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/utils/MediaUtils.java
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/shippinglabels/WCShippingLabelPackageData.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/shippinglabels/WCShippingPackageCustoms.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/user/WCUserMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/user/WCUserModel.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/user/WCUserRole.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/shippinglabels/ShippingLabelRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/user/WCUserMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/user/WCUserRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/WCUserSqlUtils.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCShippingLabelStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCUserStore.kt
  settings.gradle
Labels: Releases
