Repository wordpress-mobile/WordPress-FluxC-Android, pull requests merged in 2022-08, with the labels that each got.

#2472 Use Buildkite for CI
  .buildkite/connected-tests.sh
  .buildkite/pipeline.yml
  .buildkite/unit-tests.sh
  .buildkite/woocommerce-tests.sh
  .configure
  .configure-files/firebase.secrets.json.enc
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_MediaTestWPCom.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_MediaTestXMLRPC.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_SiteTestWPCom.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_ThemeTestWPCom.java
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_TimeStatsTestWPCom.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/utils/CommentErrorUtils.java
  gradle.properties-example
  settings.gradle
Labels: [Type] enhancement, Tooling

#2171 Encode email delimiter chars defined in RFC 3986
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/account/AccountRestClient.java
  fluxc/src/main/java/org/wordpress/android/fluxc/utils/extensions/StringExtensions.kt
Labels: [Type] enhancement, [Store] Account

#2474 [Gutenberg] EditorTheme - Add List block V2 flag
  fluxc/src/main/java/org/wordpress/android/fluxc/model/EditorTheme.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/EditorThemeSqlUtils.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
Labels: [Type] enhancement

#2481 Remove CircleCI Configuration
  .buildkite/connected-tests.sh
  .circleci/config.yml
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_WCOrderListTest.kt
Labels: Tooling

#2475 Send remote payload error when updateOrderStatus fails
  example/src/test/java/org/wordpress/android/fluxc/wc/order/WCOrderStoreTest.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCOrderStore.kt
Labels: [Type] bug, [Store] Woo: Order

#2482 [Add Detekt] 1.21.0 Integration
  .buildkite/pipeline.yml
  README.md
  build.gradle
  config/detekt/baseline.xml
  config/detekt/detekt.yml
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
Labels: Tech debt, Tooling, dependency update

#2484 [Add Detekt] Remove KtLint
  .buildkite/pipeline.yml
  README.md
  build.gradle
Labels: Tech debt, Tooling

#2489 [Tooling/CI] Update CI pipeline to group steps + add missing step dependencies
  .buildkite/pipeline.yml
Labels: Tooling

#2491 [Detekt Baseline Warnings] FluxC Module - Resolve/Suppress Complexity & Naming Warnings
  config/detekt/baseline.xml
  fluxc/src/main/java/org/wordpress/android/fluxc/model/LikeModel.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/activity/RewindStatusModel.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/layouts/GutenbergLayoutCategoriesModel.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/list/PagedListWrapper.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/revisions/RevisionModel.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/stats/InsightsMapper.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/stats/PostDetailStatsMapper.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/stats/time/TimeStatsMapper.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/WPAPIGsonRequestBuilder.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/account/AuthOptionsResponse.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/account/DomainContactResponse.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/activity/ActivityLogRestClient.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/common/LikeWPComRestResponse.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/jetpacktunnel/JetpackTunnelGsonRequest.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/jetpacktunnel/JetpackTunnelGsonRequestBuilder.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/notifications/NotificationApiResponse.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/notifications/NotificationHashApiResponse.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/notifications/NotificationHashesApiResponse.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/notifications/NotificationSeenApiResponse.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/notifications/NotificationsApiResponse.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/planoffers/PlanOffersRestClient.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/PostWPComRestResponse.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/revisions/RevisionsResponse.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/scan/threat/FixThreatsStatusDeserializer.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/scan/threat/ThreatContextDeserializer.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/DomainAvailabilityResponse.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/DomainsResponse.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClient.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/transactions/TransactionsRestClient.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/XMLRPCRequestBuilder.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/ActivityLogSqlUtils.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/ScanSqlUtils.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/SiteSqlUtils.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/StatsRequestSqlUtils.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/comments/CommentsDao.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/CommentsStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginCoroutineStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/ReactNativeStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/stats/insights/LatestPostInsightsStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/stats/time/ReferrersStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/tools/FormattableContentMapper.kt
Labels: Tech debt, Tooling

#2493 [Detekt Baseline Warnings] FluxC Module - Resolve/Suppress Other Warnings
  config/detekt/baseline.xml
  fluxc/src/main/java/org/wordpress/android/fluxc/model/EditorTheme.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/EncryptedLogUploadRequest.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/WPAPIEncodedBodyRequest.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/activity/ActivityTypesDeserializer.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/media/wpv2/WPV2MediaRestClient.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/PostWPComRestResponse.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/scan/threat/FixThreatsStatusDeserializer.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/scan/threat/FixableDeserializer.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/scan/threat/RowsDeserializer.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/scan/threat/ThreatContextDeserializer.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClient.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/XMLRPCRequestBuilder.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/PlanOffersDao.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/PlanOffersSqlUtils.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/ScanSqlUtils.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/ThreatSqlUtils.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/EncryptedLogStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/QuickStartStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/ScanStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/WhatsNewStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/bloggingprompts/BloggingPromptsStore.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/dashboard/CardsStore.kt
Labels: Tech debt, Tooling

#2492 Add PUT/POST endpoint in fluxc to support enabling/disabling Cash on Delivery as payment method
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/wc/GatewayRestClientTest.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/gateways/GatewayRestClient.kt
Labels: [Store] Woo: Pay

#2501 Add updatePaymentGateway function to WCGatewayStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCGatewayStore.kt
Labels: [Store] Woo: Pay

#2494 [Detekt Baseline Warnings] Plugins Woo Commerce Module - Resolve/Suppress Style Warnings
  config/detekt/baseline.xml
  example/src/test/java/org/wordpress/android/fluxc/wc/stats/WCStatsStoreTest.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/di/WCDatabaseModule.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/WCProductModel.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/WCProductReviewModel.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/WCProductVariationModel.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/order/LineItem.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/payments/inperson/WCPaymentChargeApiResult.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/leaderboards/LeaderboardProductItem.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderDtoMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/product/ProductRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/ProductSqlUtils.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/dao/CouponsDao.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/mappers/ToDatabaseAddonsMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/migrations/Migrations.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCOrderFetcher.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCOrderStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCProductStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCShippingLabelStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCStatsStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WooCommerceStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/utils/DateUtils.kt
Labels: Tech debt, Tooling

#2502 [Detekt Baseline Warnings] Example Module - Resolve/Suppress Style Warnings
  config/detekt/baseline.xml
  config/detekt/detekt.yml
  example/src/main/java/org/wordpress/android/fluxc/example/CustomStatsDialog.kt
  example/src/main/java/org/wordpress/android/fluxc/example/OrderListAdapter.kt
  example/src/main/java/org/wordpress/android/fluxc/example/SiteSelectorDialog.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ThreeEditTextDialog.kt
  example/src/main/java/org/wordpress/android/fluxc/example/WCAddOrderShipmentTrackingDialog.kt
  example/src/main/java/org/wordpress/android/fluxc/example/WCOrderListActivity.kt
  example/src/main/java/org/wordpress/android/fluxc/example/di/FragmentsModule.kt
  example/src/main/java/org/wordpress/android/fluxc/example/di/MainActivityModule.kt
  example/src/main/java/org/wordpress/android/fluxc/example/di/WCOrderListActivityModule.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/ListSelectorDialog.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/StoreSelectorDialog.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/customer/search/WooCustomersSearchAdapter.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/orders/WooOrdersFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooProductAttributeFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooProductCategoriesAdapter.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooProductDownloadsFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooProductTagsAdapter.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooUpdateProductFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/shippinglabels/WooShippingLabelFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/stats/WooStatsFragment.kt
  example/src/test/java/org/wordpress/android/fluxc/comment/CommentSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/comments/CommentsXMLRPCClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteHomepageRestClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/stats/InsightsRestClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/page/PageStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/store/ReactNativeStoreWPAPITest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/product/WCProductStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/shippinglabels/WCShippingLabelStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/stats/WCStatsStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/user/WCUserTestUtils.kt
Labels: Tech debt, Tooling

#2503 Use apiKey from the GatewayId enum for constructing the URL.
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/gateways/GatewayRestClient.kt
Labels: [Store] Woo: Pay

#2498 [Detekt Baseline Warnings] Plugins Woo Commerce Module - Resolve/Suppress Complexity & Naming Warnings
  config/detekt/baseline.xml
  example/src/androidTest/java/org/wordpress/android/fluxc/mocked/MockedStack_WCProductsTest.kt
  example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_WCProductTest.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/WCProductModel.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/WCRevenueStatsModel.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/customer/WCCustomerMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/payments/inperson/WCPaymentChargeApiResult.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/addons/mappers/RemoteAddonMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/coupons/CouponRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderDto.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderDtoMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderNoteApiResponse.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderShipmentTrackingApiResponse.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/orderstats/OrderStatsRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/product/ProductApiResponse.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/product/ProductRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/product/ProductReviewApiResponse.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/product/ProductVariationApiResponse.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/refunds/RefundRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/shippinglabels/ShippingLabelRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/ProductSqlUtils.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/mappers/FromDatabaseAddonsMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/migrations/Migrations.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/OrderUpdateStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCOrderStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCProductStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCShippingLabelStore.kt
  plugins/woocommerce/src/test/java/org/wordpress/android/fluxc/store/ProvideAddonsIntegrationTests.kt
Labels: Tech debt, Tooling

#2505 Added description field to the COD enable POST request
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/gateways/GatewayRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCGatewayStore.kt
Labels: [PR] Not Ready For Merge, [Store] Woo: Pay

#2500 Recover from metadata null key
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/WCMetaData.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderMappingConst.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/StripOrder.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/StripOrderMetaData.kt
  plugins/woocommerce/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/StripOrderMetaDataTest.kt
Labels: [Store] Woo: Order, [Type] Crash

#2506 [Detekt Baseline Warnings] Plugins Woo Commerce Module - Resolve/Suppress Other Warnings
  config/detekt/baseline.xml
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/WCProductModel.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/coupons/CouponRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/product/ProductRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCInboxStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCOrderStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WooCommerceStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/utils/DateUtils.kt
  plugins/woocommerce/src/test/java/org/wordpress/android/fluxc/utils/JsonObjectBuilder.kt
Labels: Tech debt, Tooling

#2504 [Detekt Baseline Warnings] Example Module - Resolve/Suppress Complexity & Naming Warnings
  config/detekt/baseline.xml
  example/src/main/java/org/wordpress/android/fluxc/example/NotificationsFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ThemeFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/WCOrderListActivity.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/WooCommerceFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/coupons/WooCouponsFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/coupons/WooUpdateCouponFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/orders/AddressEditDialogFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/orders/WooOrdersFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooBatchUpdateVariationsFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooProductsFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooUpdateProductFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooUpdateVariationFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/refunds/WooRefundsFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/shippinglabels/WooShippingLabelFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/stats/WooRevenueStatsFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/stats/WooStatsFragment.kt
  example/src/test/java/org/wordpress/android/fluxc/common/CommentsMapperTest.kt
  example/src/test/java/org/wordpress/android/fluxc/list/post/PostListDescriptorTest.kt
  example/src/test/java/org/wordpress/android/fluxc/model/customer/WCCustomerMapperTest.kt
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/stats/InsightsRestClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/notifications/NotificationSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/utils/JsonObjectExtensionsTests.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/product/ProductSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/shippinglabels/WCShippingLabelStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/stats/WCStatsSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/stats/WCStatsStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/stats/WCVisitorStatsSqlUtilsTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/utils/WCCurrencyUtilsTest.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/comments/CommentsDao.kt
Labels: Tech debt, Tooling

#2507 [Detekt Baseline Warnings] Example Module - Resolve/Suppress Other Warnings
  README.md
  build.gradle
  config/detekt/baseline.xml
  example/src/main/java/org/wordpress/android/fluxc/example/ExperimentsFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ReactNativeFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/WooCommerceFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/customer/search/WooCustomersSearchBuilderFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/gateways/WooGatewaysFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/leaderboards/WooLeaderboardsFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/orders/WooOrdersFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooBatchUpdateVariationsFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooProductAttributeFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooUpdateProductFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/refunds/WooRefundsFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/shippinglabels/WooShippingLabelFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/ui/taxes/WooTaxFragment.kt
  example/src/main/java/org/wordpress/android/fluxc/example/utils/EditTextExt.kt
  example/src/main/java/org/wordpress/android/fluxc/example/utils/JavaCoroutineHelper.kt
  example/src/test/java/org/wordpress/android/fluxc/network/RetryOnRedirectBasicNetworkTest.kt
Labels: Tech debt, Tooling

#2509 Fetch list plugins by name
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/PluginSqlUtils.java
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WooCommerceStore.kt
Labels: [Type] enhancement, [Store] Woo: Order

#2510 Add a field to allow updating instructions when COD is enabled.
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/gateways/GatewayRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCGatewayStore.kt
Labels: [Store] Woo: Pay

#2517 Save shippingPhone value in OrderEntity
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderDtoMapper.kt
Labels: [Type] bug, [Store] Woo: Order
