Repository wordpress-mobile/WordPress-FluxC-Android, pull requests merged in 2022-10, with the labels that each got.

#2535 Wrong visitor stats in WooCommerce app for yearly granularity
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCStatsStore.kt
Labels: [Type] bug

#2533 Updates the target sdk version to 31 for Android 12 migration
  fluxc/build.gradle
Labels: [PR] Not Ready For Merge, Tech debt

#2537 Patch cookiemanager
  example/src/test/java/org/wordpress/android/fluxc/network/OpenJdkCookieManagerTest.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/module/ReleaseNetworkModule.java
  fluxc/src/main/java/org/wordpress/android/fluxc/network/OpenJdkCookieManager.java
Labels: [Type] bug

#2546 fix: crash on getting `UserAgent` on thread different than the main
  fluxc/src/main/java/org/wordpress/android/fluxc/network/UserAgent.java
Labels: [Type] Crash

#2545 Implementation to fetch JITM messages
  example/src/androidTest/java/org/wordpress/android/fluxc/mocked/MockedNetworkAppComponent.java
  example/src/androidTest/java/org/wordpress/android/fluxc/mocked/MockedStack_JitmTest.kt
  example/src/androidTest/resources/jitm-fetch-failure.json
  example/src/androidTest/resources/jitm-fetch-success-empty.json
  example/src/androidTest/resources/jitm-fetch-success.json
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/jitm/JitmRestClientTest.kt
  fluxc-annotations/src/main/java/org/wordpress/android/fluxc/annotations/endpoint/WPComEndpoint.java
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/jitm/JitmRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/payments/inperson/JITMApiResponse.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/JitmStore.kt
Labels: [Store] Woo: Pay

#2547 Top performers with date period
  example/src/test/java/org/wordpress/android/fluxc/wc/leaderboards/LeaderboardsRestClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/leaderboards/WCLeaderboardsStoreTest.kt
  example/src/test/java/org/wordpress/android/fluxc/wc/leaderboards/WCProductLeaderboardsMapperTest.kt
  plugins/woocommerce/src/androidTest/java/org/wordpress/android/fluxc/persistence/MigrationTests.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/leaderboards/WCProductLeaderboardsMapper.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/leaderboards/LeaderboardsRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/WCAndroidDatabase.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/dao/TopPerformerProductsDao.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/entity/TopPerformerProductEntity.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/migrations/Migrations.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCLeaderboardsStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCStatsStore.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/utils/DateUtils.kt
Labels: [Store] Woo: Stats

#2552 Implement JITM dismiss api
  example/src/androidTest/java/org/wordpress/android/fluxc/mocked/MockedStack_JitmTest.kt
  example/src/androidTest/resources/jitm-dismiss-failure.json
  example/src/androidTest/resources/jitm-dismiss-success.json
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/jitm/JitmRestClientTest.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/jitm/JITMApiResponse.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/jitm/JitmRestClient.kt
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/JitmStore.kt
Labels: [Store] Woo: Pay

#2553 JITM Rest Client unit test for dismissal logic
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/jitm/JitmRestClientTest.kt
Labels: [Store] Woo: Pay
