Repository wordpress-mobile/WordPress-FluxC-Android, pull requests merged in 2024-01, with the labels that each got.

#2933 Blaze/mock target endpoints
  example/src/test/java/org/wordpress/android/fluxc/store/blaze/BlazeCampaignsStoreTest.kt
  fluxc/schemas/org.wordpress.android.fluxc.persistence.WPAndroidDatabase/24.json
  fluxc/src/main/java/org/wordpress/android/fluxc/model/blaze/BlazeTargetingDevice.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/blaze/BlazeTargetingLanguage.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/blaze/BlazeTargetingLocation.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/model/blaze/BlazeTargetingTopic.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/module/DatabaseModule.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/blaze/FakeBlazeTargetingRestClient.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WPAndroidDatabase.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/blaze/BlazeTargetingDao.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/blaze/BlazeCampaignsStore.kt
Labels: Blaze

#2937 Fix locale issue for v3 endpoints.
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/BaseWPComRestClient.java
Labels: [Type] bug

#2938 Fix locale issue for v3 endpoints keeping previous fallback to locale
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/BaseWPComRestClient.java
Labels: [Type] bug

#2935 🤖 Add backend-driven Dynamic Cards filtering
  example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/dashboard/CardsRestClientTest.kt
  example/src/test/java/org/wordpress/android/fluxc/store/dashboard/CardsStoreTest.kt
  example/src/test/resources/wp/dashboard/cards.json
  fluxc/src/main/java/org/wordpress/android/fluxc/model/dashboard/CardModel.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/dashboard/CardsRestClient.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/dashboard/CardsStore.kt
Labels: [Type] enhancement, Dynamic cards, [Store] Dashboard Cards

#2940 Cherry picking #2938 in 2.59.2
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/BaseWPComRestClient.java
Labels: [Type] bug

#2941 Implement unit tests for BaseWPComRestClient locale query parameter decision
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/BaseWPComRestClient.java
  fluxc/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/BaseWPComRestClientTest.java
Labels: [Type] enhancement

#2943 Fix visitors cast exception
  example/src/test/java/org/wordpress/android/fluxc/wc/stats/WCStatsStoreTest.kt
  example/src/test/resources/wc/wrong-visitor-stats-data.json
  plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCStatsStore.kt
Labels: [Store] Woo: Stats, [Type] Crash

#2947 Add Blaze ad suggestion network/persistence layer
  example/src/test/java/org/wordpress/android/fluxc/store/blaze/BlazeCampaignsStoreTest.kt
  fluxc/schemas/org.wordpress.android.fluxc.persistence.WPAndroidDatabase/25.json
  fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/blaze/FakeBlazeTargetingRestClient.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WPAndroidDatabase.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/persistence/blaze/BlazeCampaignsDao.kt
  fluxc/src/main/java/org/wordpress/android/fluxc/store/blaze/BlazeCampaignsStore.kt
Labels: [Store] WooCommerce

#2946 [Fix] Update target sdk from 33 to 34.
  build.gradle
  settings.gradle
Labels: Android 14
